### ISSUE TITLE
链接失效：iOS提高效率的方法和工具 - iOS提高效率的方法和工具

### ISSUE THREAD

**Issue by fhefh2009** [Tim9Liu9/TimLiu-iOS#1]
链接失效：iOS提高效率的方法和工具 - iOS提高效率的方法和工具
http://lcepy.github.io/2015/07/14/iOS%E6%8F%90%E9%AB%98%E6%95%88%E7%8E%87%E7%9A%84%E6%96%B9%E6%B3%95%E5%92%8C%E5%B7%A5%E5%85%B7/
=================================
404
There isn't a GitHub Pages site here.

**Comment by tasselx** [comment]
@fhefh2009 https://github.com/icepy/_posts/blob/master/iOS%E6%8F%90%E9%AB%98%E6%95%88%E7%8E%87%E7%9A%84%E6%96%B9%E6%B3%95%E5%92%8C%E5%B7%A5%E5%85%B7.md

**Comment by Tim9Liu9** [comment]
已经修正，多谢。
