### ISSUE TITLE
帅哥、美女，能给我更大的权限和你一起维护这个三方库吗?

### ISSUE THREAD

**Issue by mrhyh** [Tim9Liu9/TimLiu-iOS#27]

**Comment by mrhyh** [comment]
很遗憾，不能得到你的允许跟你一起维护这个库，不过你的库真的很棒，那我自己fork一份处理吧.

**Comment by Tim9Liu9** [comment]
不好意思，今天才回复，我最近做后台开发了，对客户端开发关注很少了，我本人非常欢迎与你一起维护这个库，造福开发者，请加我qq:9925124 注明github库维护。


发自 网易邮箱大师
在2016年07月16日 04:04，ylgwhyh 写道:

Closed #27.

**Comment by mrhyh** [comment]
很高兴能和你一起合作，只是我fork你的库，改动稍有点大，不过仅仅是改动，不是删除（仅仅删除了少数一些不能用的库）。然后我将Objective-C和Swift分开了，你觉得怎样呢？

**Comment by mrhyh** [comment]
你给我完全的更改权限吗？再动手更改之前还是再问问你 @Tim9Liu9 ，等待你的回复。

**Comment by Tim9Liu9** [comment]
不用征求我意见，直接修改。


发自 网易邮箱大师
在2016年08月12日 11:17，ylgwhyh 写道:

你给我完全的更改权限吗？再动手更改之前还是再问问你 @Tim9Liu9 ，等待你的回复。
