### ISSUE TITLE
意见征集

### ISSUE THREAD

**Issue by mrhyh** [Tim9Liu9/TimLiu-iOS#44]
这是一个给我们广大iOS开发者使用的三方库集合，如果有幸迎来您的光临，希望能提出一些宝贵的意见，以便我们更好的进行维护.

**Comment by heyehao2008** [comment]
希望去掉一些久不更新的库，比如一两年之内都没有更新过的库。因为iOS版本迭代很快，两年不更新很多东西都已经变了。没必要在收录了

**Comment by mrhyh** [comment]
谢谢您的建议，这个已经在做了哈，大概会在这个月底前完成.

**Comment by nibaJin** [comment]
FJTag的那个 github上修正过了

**Comment by mrhyh** [comment]
不太明白什么意思？FJTag是一个三方库吗？

**Comment by AndyHT** [comment]
在排版上我觉得这个更好一点➡️https://github.com/ipader/SwiftGuide/blob/master/Featured.md
但是这个列表好久没人维护了，好多库都只是swift1.0或者2.0的库，内容也比较少

**Comment by mrhyh** [comment]
这个库的排版确实很好，部分栏目可以使用

**Comment by Andy0570** [comment]
网络连接@ HYBNetworking这个框架重复放了2次。

**Comment by mrhyh** [comment]
好的，已经移除重复的
