### ISSUE TITLE
截止2016-11月月底的工作

### ISSUE THREAD

**Issue by mrhyh** [Tim9Liu9/TimLiu-iOS#45]
对整个项目进行一次彻底的整理，方便大家使用.

**Comment by sabatian** [comment]
好人啊 亲

**Comment by sabatian** [comment]
对于iOS开发，我还是初学者，希望能够和你学习到更多。

**Comment by mrhyh** [comment]
这个库里有很多前辈高人哈，我也是跟这些前辈们学习一下而已哈.

**Comment by rickyhust** [comment]
楼主有计划写一份Mac App开发的开源库的总结吗？
最近开始接触Mac App的开发，发现比较痛苦，NSButton像设置一个背景色和Title颜色都很麻烦。。

**Comment by mrhyh** [comment]
没有呢，不过这里有一个不错的关于Mac App开发的三方库集合：https://github.com/iCHAIT/awesome-osx

**Comment by AndyHT** [comment]
swift版本里有好多标题跳转失效，我可以帮忙fix，直接提交pr可以嘛？

**Comment by mrhyh** [comment]
可以哈，你直接提交，我收到马上就处理了

**Comment by mrhyh** [comment]
不过那些标题不要删除哈，那个以后要添加内容的，可以先注释掉

**Comment by mrhyh** [comment]
真遗憾，这个月略微有点忙，没能实现11月份制定的计划，我会尽快完成的.

**Comment by mrhyh** [comment]
已经整理完了，这个时间拖得有点久啊，移除了超过1年未更新的所有库。
