### ISSUE TITLE
可以添加 reaml 数据库插件

### ISSUE THREAD

**Issue by chenjiev1** [Tim9Liu9/TimLiu-iOS#63]
https://github.com/realm/realm-cocoa

**Comment by mrhyh** [comment]
@chenjiev1  已经添加了，谢谢

**Comment by chenjiev1** [comment]
@mrhyh 建议在readme.md中也添加 
不过我看swift已经有reaml了。打扰了

**Comment by mrhyh** [comment]
Objective-c和Swift都添加了的
