### ISSUE TITLE
链接失效

### ISSUE THREAD

**Issue by zhutongLILY** [Tim9Liu9/TimLiu-iOS#69]
[iOS完整App资源收集](http://www.henishuo.com/ios-app-fully-code/) - iOS开发学习者都希望得到实战训练，但是很多资料都是只有一小部分代码，并不能形成完成的App，笔者在此处收集了很多开源的完整的App，都有源代码哦！--标哥的技术博客
这个对应的链接失效了，

**Comment by mrhyh** [comment]
谢谢您提出发现的问题，已经修复了
