### ISSUE TITLE
讨论：在每个库后台添加了库的相关数据---- (Star:23,401) (Fork:3,460) (Watch:1,178)，大家怎么看？

### ISSUE THREAD

**Issue by mrhyh** [Tim9Liu9/TimLiu-iOS#78]
虽然添加这些数据是给大家参考的，但我始终觉得有些问题，因为我们开源项目是为了学习、交流的，并非为了攀比start等等。我担心大家的注意力都集中到start等等的数据去了，而忽略了开源学习的根本.希望大家能讨论下，给点参考意见.

**Comment by NSaylor** [comment]
最初提出这个建议是希望能够当前超长的列表中，很直观看到库的 发布时间（描述更新频率之类的） 以及活跃度（如issue 提交数等等）。  
这些数据（start等等）应该是可以 转换成 这些指标的~~~

**Comment by mrhyh** [comment]
确实可以拿到这些数据，就是这样做之后似乎会让大家把注意力转到这个上面去了，开源的根本是相互学习交流，而这个库的存在是为了方便国内iOS开发者更方便的学习，加上那些数据之后，让这个库变的内容变得有点冗余、繁杂，所以只添加了一天就去掉了.

**Comment by NSaylor** [comment]
深深的理解
