### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by hustcc** [Tim9Liu9/TimLiu-iOS#9]
很好的项目，但是为啥不做成格式为定义好的json数据，然后做一个前端网页来显示这些iOS库。

这样可以吸引大家来pr，类似于cdnjs、microjs.com一样，可以收集很多好的开发库，同时自己的维护工作量也会小一些。

**Comment by iMuFeng** [comment]
这个想法不错

**Comment by hustcc** [comment]
嗯，我最近有些这种想法，还么有成熟，另外，也没有想你这样高关注的repo。
